# Run the Catnap feasibility test, this involves measuring over an adc
# Otherwise we'll run Culpeo
CATNAP_FEASIBILITY ?= 0

# Settings for debugging, these should all be set to 0 for tests

# Run on continuous power, stops looking at the comparator
CATNAP_RUN_CONT = 0
# Disable Culpeo's event profiling
CULPEO_PROF_DISABLE = 0
# Enable/disable debug prints
LIBFCN_DEBUG = 0


# Comparator GPIO port/pin definitions
LIBFCN_COMP_PIN_PORT = 3
LIBFCN_COMP_PIN_PIN = 1


# COMP_THRESHOLD can be defined in application
# TODO make this transalation happen automatically
# Note-- upper hysteresis threshold should be 10mV (or whatever) above event
# threshold all the time
CATNAP_EVENT_THRESHOLD ?= V_2_20
CATNAP_TASK_UPPER_HYST ?= V_2_30

# TODO make this multiplication happen in makefile
CATNAP_ADC_THRESHOLD ?= 220
CULPEO_ADC_THRESHOLD ?= 2200

