# Run the Catnap feasibility test, this involves measuring over an adc
# Otherwise we'll run Culpeo
CATNAP_FEASIBILITY = 0

# Run on continuous power, stops looking at the comparator
CATNAP_RUN_CONT = 0

# Comparator GPIO port/pin definitions
LIBFCN_COMP_PIN_PORT = 3
LIBFCN_COMP_PIN_PIN = 1

# Enable/disable debug prints
LIBFCN_DEBUG = 0
